In [9]:
import numpy as np 
numbers = np.array([55,4,6,3])
#print(numbers)
numbers


array([55,  4,  6,  3])

In [11]:
np1 = np.array([2,3,4,5,6,7,8])
np1

array([2, 3, 4, 5, 6, 7, 8])

In [57]:
import numpy as np
np1 = np.array([1,2,3])
np2 = np.array([[2,3,4],[5,6,70],[9,8,1]])
np3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[10,11]]])
print(np3.ndim)
print(np3.size)
print(np3.shape)
np4 = np3.reshape(3,4)
print(np4)
#print(np1)
#print(np2)
#print(np3)

3
12
(3, 2, 2)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 11]]


In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.zeros(4)

array([0., 0., 0., 0.])

In [25]:
np.empty(4)

array([0., 0., 0., 0.])

In [27]:
arr = np.array([1,2,4,5,7,0,1])
np.sort(arr)

array([0, 1, 1, 2, 4, 5, 7])

In [28]:
np8 = np.array([2,3,5,6,7,9])
type(np8)

numpy.ndarray

In [29]:
np.linspace(0,10,num = 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [41]:
arr2  = np.array([1,5,2,0,8,7,3])
arr3 = np.array([10,11,12,13,14])
np.concatenate((arr2,arr3),axis = 0)
np.concatenate((arr2,arr3))

array([ 1,  5,  2,  0,  8,  7,  3, 10, 11, 12, 13, 14])